name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user files
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Build Project
        run: |
          # حفظ ملف main.dart الذي كتبته
          cp lib/main.dart /tmp/main.dart
          
          # إنشاء مشروع Flutter أندرويد جديد بجميع الإعدادات المطلوبة
          cd ..
          flutter create --org com.example staff_app
          
          # استبدال ملف main.dart وإضافة حزمة اللغات
          cp /tmp/main.dart staff_app/lib/main.dart
          cd staff_app
          flutter pub add flutter_localizations --sdk=flutter
          flutter pub add intl
          
          # بناء ملف APK
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: staff_manager_app
          path: ../staff_app/build/app/outputs/flutter-apk/app-release.apk
